### ISSUE TITLE
e.VIper.ReadInConfig run as part of Unmarshal clears merged in fields

### ISSUE THREAD

**Issue by jkosecki** [iamolegga/enviper#12]
Hi,

due to `e.Viper.ReadInConfig()` that is invoked as part of `Enviper#Unmarshal` any additional fields added via `Viper#MergeConfigMap` method are cleared. That prevents usage like that:
```
        e := enviper.New(viper.New())
	if err := e.ReadInConfig(); err != nil {
		panic(err.Error())
	}
	if err := e.MergeConfigMap(defaults.AllSettings()); err != nil {
		panic(err.Error())
	}
	if err := e.Unmarshal(&cfg); err != nil {
		panic(err.Error())
	}
```

Is there a reason why `Unmarshal` makes a call to `ReadInConfig`? Afaik, viper itself expects users to call `ReadInConfig` explicitly before `Unmarshal` is used

**Comment by iamolegga** [comment]
This was in [original solution](https://github.com/spf13/viper/issues/188#issuecomment-399884438). I actually don't remember why is this required. You could fork this repo, drop that line and run tests and see if it will work for you
